# coding: utf-8

"""
    DocSpring API

    Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.template_add_fields_response import TemplateAddFieldsResponse

class TestTemplateAddFieldsResponse(unittest.TestCase):
    """TemplateAddFieldsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateAddFieldsResponse:
        """Test TemplateAddFieldsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateAddFieldsResponse`
        """
        model = TemplateAddFieldsResponse()
        if include_optional:
            return TemplateAddFieldsResponse(
                status = 'success',
                errors = [
                    ''
                    ],
                new_field_ids = [
                    56
                    ]
            )
        else:
            return TemplateAddFieldsResponse(
                status = 'success',
        )
        """

    def testTemplateAddFieldsResponse(self):
        """Test TemplateAddFieldsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
