# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.template import Template

class TestTemplate(unittest.TestCase):
    """Template unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Template:
        """Test Template
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Template`
        """
        model = Template()
        if include_optional:
            return Template(
                add_data_request_submission_id_footers = True,
                allow_additional_properties = True,
                description = '',
                document_filename = '',
                document_md5 = '',
                document_parse_error = True,
                document_processed = True,
                document_state = 'pending',
                document_url = '',
                editable_submissions = True,
                embed_domains = '',
                encrypt_pdfs_password = '',
                encrypt_pdfs = True,
                expiration_interval = '',
                expire_after = 56,
                expire_submissions = True,
                external_predefined_fields_template_id = '',
                external_predefined_fields_template_name = '',
                first_template = True,
                id = '',
                locked = True,
                merge_audit_trail_pdf = True,
                name = '',
                page_count = 56,
                page_dimensions = [
                    [
                        1.337
                        ]
                    ],
                parent_folder_id = '',
                path = '',
                permanent_document_url = '',
                public_submissions = True,
                public_web_form = True,
                redirect_url = '',
                slack_webhook_url = '',
                template_type = 'pdf',
                updated_at = '',
                version_published_at = '',
                version = '',
                webhook_url = '',
                demo = True,
                latest_version = '',
                last_changed_at = '',
                last_changed_by_type = 'user',
                last_changed_by_id = '',
                defaults = docspring.models.template_defaults.template_defaults(),
                field_order = [
                    [
                        1.337
                        ]
                    ],
                fields = docspring.models.template_fields.template_fields(),
                footer_html = '',
                header_html = '',
                html_engine_options = docspring.models.html_engine_options.html_engine_options(),
                html = '',
                predefined_fields = [
                    docspring.models.predefined_field.predefined_field()
                    ],
                scss = '',
                shared_field_data = docspring.models.template_shared_field_data.template_shared_field_data(),
                versions = [
                    None
                    ]
            )
        else:
            return Template(
                add_data_request_submission_id_footers = True,
                allow_additional_properties = True,
                description = '',
                document_filename = '',
                document_md5 = '',
                document_parse_error = True,
                document_processed = True,
                document_state = 'pending',
                document_url = '',
                editable_submissions = True,
                embed_domains = '',
                encrypt_pdfs_password = '',
                encrypt_pdfs = True,
                expiration_interval = '',
                expire_after = 56,
                expire_submissions = True,
                external_predefined_fields_template_id = '',
                external_predefined_fields_template_name = '',
                first_template = True,
                id = '',
                locked = True,
                merge_audit_trail_pdf = True,
                name = '',
                page_count = 56,
                page_dimensions = [
                    [
                        1.337
                        ]
                    ],
                parent_folder_id = '',
                path = '',
                permanent_document_url = '',
                public_submissions = True,
                public_web_form = True,
                redirect_url = '',
                slack_webhook_url = '',
                template_type = 'pdf',
                updated_at = '',
                version_published_at = '',
                version = '',
                webhook_url = '',
                demo = True,
                latest_version = '',
                last_changed_at = '',
                last_changed_by_type = 'user',
                last_changed_by_id = '',
                defaults = docspring.models.template_defaults.template_defaults(),
                field_order = [
                    [
                        1.337
                        ]
                    ],
                fields = docspring.models.template_fields.template_fields(),
                footer_html = '',
                header_html = '',
                html_engine_options = docspring.models.html_engine_options.html_engine_options(),
                html = '',
                predefined_fields = [
                    docspring.models.predefined_field.predefined_field()
                    ],
                scss = '',
                shared_field_data = docspring.models.template_shared_field_data.template_shared_field_data(),
                versions = [
                    None
                    ],
        )
        """

    def testTemplate(self):
        """Test Template"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
