# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.submission_batch import SubmissionBatch

class TestSubmissionBatch(unittest.TestCase):
    """SubmissionBatch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmissionBatch:
        """Test SubmissionBatch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmissionBatch`
        """
        model = SubmissionBatch()
        if include_optional:
            return SubmissionBatch(
                id = '',
                state = 'pending',
                metadata = None,
                processed_at = '',
                total_count = 56,
                pending_count = 56,
                error_count = 56,
                completion_percentage = 1.337
            )
        else:
            return SubmissionBatch(
                id = '',
                state = 'pending',
                metadata = None,
                processed_at = '',
                total_count = 56,
                pending_count = 56,
                error_count = 56,
                completion_percentage = 1.337,
        )
        """

    def testSubmissionBatch(self):
        """Test SubmissionBatch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
