# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.template_publish_version_response import TemplatePublishVersionResponse

class TestTemplatePublishVersionResponse(unittest.TestCase):
    """TemplatePublishVersionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatePublishVersionResponse:
        """Test TemplatePublishVersionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatePublishVersionResponse`
        """
        model = TemplatePublishVersionResponse()
        if include_optional:
            return TemplatePublishVersionResponse(
                status = 'success',
                result = None,
                errors = [
                    ''
                    ]
            )
        else:
            return TemplatePublishVersionResponse(
                status = 'success',
                result = None,
        )
        """

    def testTemplatePublishVersionResponse(self):
        """Test TemplatePublishVersionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
