# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.submission_data_request_show import SubmissionDataRequestShow

class TestSubmissionDataRequestShow(unittest.TestCase):
    """SubmissionDataRequestShow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmissionDataRequestShow:
        """Test SubmissionDataRequestShow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmissionDataRequestShow`
        """
        model = SubmissionDataRequestShow()
        if include_optional:
            return SubmissionDataRequestShow(
                id = '',
                email = '',
                name = '',
                order = 56,
                sort_order = 56,
                fields = [
                    ''
                    ],
                metadata = None,
                state = 'pending',
                viewed_at = '',
                completed_at = '',
                data = None,
                auth_type = 'none',
                auth_second_factor_type = 'none',
                auth_provider = '',
                auth_session_started_at = '',
                auth_session_id_hash = '',
                auth_user_id_hash = '',
                auth_username_hash = '',
                auth_phone_number_hash = '',
                ip_address = '',
                user_agent = '',
                submission_id = ''
            )
        else:
            return SubmissionDataRequestShow(
                id = '',
                email = '',
                name = '',
                order = 56,
                sort_order = 56,
                fields = [
                    ''
                    ],
                metadata = None,
                state = 'pending',
                viewed_at = '',
                completed_at = '',
                data = None,
                auth_type = 'none',
                auth_second_factor_type = 'none',
                auth_provider = '',
                auth_session_started_at = '',
                auth_session_id_hash = '',
                auth_user_id_hash = '',
                auth_username_hash = '',
                auth_phone_number_hash = '',
                ip_address = '',
                user_agent = '',
                submission_id = '',
        )
        """

    def testSubmissionDataRequestShow(self):
        """Test SubmissionDataRequestShow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
