# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.batch_generate_pdfs201_response import BatchGeneratePdfs201Response

class TestBatchGeneratePdfs201Response(unittest.TestCase):
    """BatchGeneratePdfs201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchGeneratePdfs201Response:
        """Test BatchGeneratePdfs201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchGeneratePdfs201Response`
        """
        model = BatchGeneratePdfs201Response()
        if include_optional:
            return BatchGeneratePdfs201Response(
                status = 'success',
                error = '',
                errors = [
                    ''
                    ],
                submission_batch = docspring.models.submission_batch.submission_batch(
                    id = '', 
                    state = 'pending', 
                    metadata = docspring.models.metadata.metadata(), 
                    processed_at = '', 
                    total_count = 56, 
                    pending_count = 56, 
                    error_count = 56, 
                    completion_percentage = 1.337, ),
                submissions = [
                    None
                    ]
            )
        else:
            return BatchGeneratePdfs201Response(
                status = 'success',
                submission_batch = docspring.models.submission_batch.submission_batch(
                    id = '', 
                    state = 'pending', 
                    metadata = docspring.models.metadata.metadata(), 
                    processed_at = '', 
                    total_count = 56, 
                    pending_count = 56, 
                    error_count = 56, 
                    completion_percentage = 1.337, ),
                submissions = [
                    None
                    ],
        )
        """

    def testBatchGeneratePdfs201Response(self):
        """Test BatchGeneratePdfs201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
