# coding: utf-8

"""
    DocSpring API

    Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.submission_action import SubmissionAction

class TestSubmissionAction(unittest.TestCase):
    """SubmissionAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmissionAction:
        """Test SubmissionAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmissionAction`
        """
        model = SubmissionAction()
        if include_optional:
            return SubmissionAction(
                id = '',
                integration_id = '',
                state = 'pending',
                action_type = 'webhook',
                action_category = 'notification',
                result_data = docspring.models.result_data.result_data()
            )
        else:
            return SubmissionAction(
                id = '',
                integration_id = '',
                state = 'pending',
                action_type = 'webhook',
                action_category = 'notification',
                result_data = docspring.models.result_data.result_data(),
        )
        """

    def testSubmissionAction(self):
        """Test SubmissionAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
