# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.submission_batch_data import SubmissionBatchData

class TestSubmissionBatchData(unittest.TestCase):
    """SubmissionBatchData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubmissionBatchData:
        """Test SubmissionBatchData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubmissionBatchData`
        """
        model = SubmissionBatchData()
        if include_optional:
            return SubmissionBatchData(
                metadata = None,
                submissions = [
                    docspring.models.submission_data_batch_request.submission_data_batch_request()
                    ],
                test = True
            )
        else:
            return SubmissionBatchData(
                submissions = [
                    docspring.models.submission_data_batch_request.submission_data_batch_request()
                    ],
        )
        """

    def testSubmissionBatchData(self):
        """Test SubmissionBatchData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
