# coding: utf-8

"""
    DocSpring API

    Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.error_or_multiple_errors_response import ErrorOrMultipleErrorsResponse

class TestErrorOrMultipleErrorsResponse(unittest.TestCase):
    """ErrorOrMultipleErrorsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorOrMultipleErrorsResponse:
        """Test ErrorOrMultipleErrorsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorOrMultipleErrorsResponse`
        """
        model = ErrorOrMultipleErrorsResponse()
        if include_optional:
            return ErrorOrMultipleErrorsResponse(
                status = 'error',
                error = '',
                errors = [
                    ''
                    ]
            )
        else:
            return ErrorOrMultipleErrorsResponse(
                status = 'error',
        )
        """

    def testErrorOrMultipleErrorsResponse(self):
        """Test ErrorOrMultipleErrorsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
