# coding: utf-8

"""
    DocSpring API

    Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.create_pdf_submission_data import CreatePdfSubmissionData

class TestCreatePdfSubmissionData(unittest.TestCase):
    """CreatePdfSubmissionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePdfSubmissionData:
        """Test CreatePdfSubmissionData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePdfSubmissionData`
        """
        model = CreatePdfSubmissionData()
        if include_optional:
            return CreatePdfSubmissionData(
                data = docspring.models.submission_data.submission_data(),
                data_requests = [
                    docspring.models.create_submission_data_request_data.create_submission_data_request_data(
                        auth_phone_number_hash = '', 
                        auth_provider = '', 
                        auth_second_factor_type = 'none', 
                        auth_session_id_hash = '', 
                        auth_session_started_at = '', 
                        auth_type = 'none', 
                        auth_user_id_hash = '', 
                        auth_username_hash = '', 
                        email = '', 
                        fields = [
                            ''
                            ], 
                        metadata = docspring.models.metadata.metadata(), 
                        name = '', 
                        order = 56, 
                        skipped = True, )
                    ],
                editable = True,
                expires_in = 56,
                field_overrides = docspring.models.submission_field_overrides.submission_field_overrides(),
                metadata = docspring.models.submission_metadata.submission_metadata(),
                password = '',
                test = True,
                version = ''
            )
        else:
            return CreatePdfSubmissionData(
                data = docspring.models.submission_data.submission_data(),
        )
        """

    def testCreatePdfSubmissionData(self):
        """Test CreatePdfSubmissionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
