# coding: utf-8

"""
    DocSpring API

    DocSpring provides an API that helps you fill out and sign PDF templates.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.success_multiple_errors_response import SuccessMultipleErrorsResponse

class TestSuccessMultipleErrorsResponse(unittest.TestCase):
    """SuccessMultipleErrorsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SuccessMultipleErrorsResponse:
        """Test SuccessMultipleErrorsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SuccessMultipleErrorsResponse`
        """
        model = SuccessMultipleErrorsResponse()
        if include_optional:
            return SuccessMultipleErrorsResponse(
                status = 'success',
                errors = [
                    ''
                    ]
            )
        else:
            return SuccessMultipleErrorsResponse(
                status = 'success',
        )
        """

    def testSuccessMultipleErrorsResponse(self):
        """Test SuccessMultipleErrorsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
