# coding: utf-8

"""
    DocSpring API

    Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.template_preview import TemplatePreview

class TestTemplatePreview(unittest.TestCase):
    """TemplatePreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatePreview:
        """Test TemplatePreview
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatePreview`
        """
        model = TemplatePreview()
        if include_optional:
            return TemplatePreview(
                add_data_request_submission_id_footers = True,
                allow_additional_properties = True,
                description = '',
                document_filename = '',
                document_md5 = '',
                document_parse_error = True,
                document_processed = True,
                document_state = 'pending',
                document_url = '',
                editable_submissions = True,
                embed_domains = '',
                encrypt_pdfs_password = '',
                encrypt_pdfs = True,
                expiration_interval = '',
                expire_after = 56,
                expire_submissions = True,
                external_predefined_fields_template_id = '',
                external_predefined_fields_template_name = '',
                first_template = True,
                id = '',
                locked = True,
                merge_audit_trail_pdf = True,
                name = '',
                page_count = 56,
                page_dimensions = [
                    [
                        1.337
                        ]
                    ],
                parent_folder_id = '',
                path = '',
                permanent_document_url = '',
                public_submissions = True,
                public_web_form = True,
                redirect_url = '',
                slack_webhook_url = '',
                template_type = 'pdf',
                updated_at = '',
                version_published_at = '',
                version = '',
                webhook_url = '',
                demo = True,
                latest_version = '',
                last_changed_at = '',
                last_changed_by_type = 'user',
                last_changed_by_id = ''
            )
        else:
            return TemplatePreview(
                add_data_request_submission_id_footers = True,
                allow_additional_properties = True,
                description = '',
                document_filename = '',
                document_md5 = '',
                document_parse_error = True,
                document_processed = True,
                document_state = 'pending',
                document_url = '',
                editable_submissions = True,
                embed_domains = '',
                encrypt_pdfs_password = '',
                encrypt_pdfs = True,
                expiration_interval = '',
                expire_after = 56,
                expire_submissions = True,
                external_predefined_fields_template_id = '',
                external_predefined_fields_template_name = '',
                first_template = True,
                id = '',
                locked = True,
                merge_audit_trail_pdf = True,
                name = '',
                page_count = 56,
                page_dimensions = [
                    [
                        1.337
                        ]
                    ],
                parent_folder_id = '',
                path = '',
                permanent_document_url = '',
                public_submissions = True,
                public_web_form = True,
                redirect_url = '',
                slack_webhook_url = '',
                template_type = 'pdf',
                updated_at = '',
                version_published_at = '',
                version = '',
                webhook_url = '',
                demo = True,
                latest_version = '',
                last_changed_at = '',
                last_changed_by_type = 'user',
                last_changed_by_id = '',
        )
        """

    def testTemplatePreview(self):
        """Test TemplatePreview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
