# coding: utf-8

"""
    DocSpring API

    Use DocSpring's API to programmatically fill out PDF forms, convert HTML to PDFs, merge PDFs, or request legally binding e-signatures.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from docspring.models.create_submission_data_request_token_response import CreateSubmissionDataRequestTokenResponse

class TestCreateSubmissionDataRequestTokenResponse(unittest.TestCase):
    """CreateSubmissionDataRequestTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSubmissionDataRequestTokenResponse:
        """Test CreateSubmissionDataRequestTokenResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSubmissionDataRequestTokenResponse`
        """
        model = CreateSubmissionDataRequestTokenResponse()
        if include_optional:
            return CreateSubmissionDataRequestTokenResponse(
                status = 'success',
                token = docspring.models.submission_data_request_token.submission_data_request_token(
                    id = '', 
                    secret = '', 
                    expires_at = '', 
                    data_request_url = '', ),
                errors = [
                    ''
                    ]
            )
        else:
            return CreateSubmissionDataRequestTokenResponse(
                status = 'success',
                token = docspring.models.submission_data_request_token.submission_data_request_token(
                    id = '', 
                    secret = '', 
                    expires_at = '', 
                    data_request_url = '', ),
        )
        """

    def testCreateSubmissionDataRequestTokenResponse(self):
        """Test CreateSubmissionDataRequestTokenResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
